[workspace]
resolver = "2"

members = [
  "selfie",
  "selfie-lexer",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
logos             = "0.13.0"
nom               = "7.1.3"
ordered-float     = "4.1.1"
pretty_assertions = "1.4.0"
thiserror         = "1.0.40"
