[package]
name = "selfie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.13.0"
nom = "7.1.3"
ordered-float = "4.1.1"
thiserror = "1.0.40"

[dev-dependencies]
pretty_assertions = "1.4.0"
