[package]
name    = "selfie-lsp"
version = "0.1.0"

edition.workspace = true

[dependencies]
lsp-positions = "0.3.2"
lsp-server = "0.7.4"
lsp-types = "0.94.1"

serde = { version = "1", features = ["derive"] }
serde_json = "1"
