[package]
name = "selfie-ast"

version.workspace = true
edition.workspace = true

[dependencies]
selfie-lexer = { path = "../selfie-lexer" }

chumsky.workspace       = true
ordered-float.workspace = true
indexmap.workspace      = true
ustr.workspace          = true
